/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MyApplicationsRouteImport } from './routes/my-applications'
import { Route as MyAccountRouteImport } from './routes/my-account'
import { Route as HousingCounselorsRouteImport } from './routes/housing-counselors'
import { Route as GetAssistanceRouteImport } from './routes/get-assistance'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocumentChecklistRouteImport } from './routes/document-checklist'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as AdditionalResourcesRouteImport } from './routes/additional-resources'
import { Route as AccountRouteImport } from './routes/account'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as ListingsForSaleRouteImport } from './routes/listings.for-sale'
import { Route as ListingsForRentRouteImport } from './routes/listings.for-rent'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AccountApplicationsRouteImport } from './routes/account.applications'
import { Route as LangSignInRouteImport } from './routes/$lang/sign-in'
import { Route as LangResetPasswordRouteImport } from './routes/$lang/reset-password'
import { Route as LangPrivacyRouteImport } from './routes/$lang/privacy'
import { Route as LangMyApplicationsRouteImport } from './routes/$lang/my-applications'
import { Route as LangMyAccountRouteImport } from './routes/$lang/my-account'
import { Route as LangHousingCounselorsRouteImport } from './routes/$lang/housing-counselors'
import { Route as LangGetAssistanceRouteImport } from './routes/$lang/get-assistance'
import { Route as LangForgotPasswordRouteImport } from './routes/$lang/forgot-password'
import { Route as LangDocumentChecklistRouteImport } from './routes/$lang/document-checklist'
import { Route as LangDisclaimerRouteImport } from './routes/$lang/disclaimer'
import { Route as LangCreateAccountRouteImport } from './routes/$lang/create-account'
import { Route as LangAdditionalResourcesRouteImport } from './routes/$lang/additional-resources'
import { Route as LangAccountRouteImport } from './routes/$lang/account'
import { Route as ListingsIdNextStepsRouteImport } from './routes/listings.$id.next-steps'
import { Route as ListingsIdHowToApplyRouteImport } from './routes/listings.$id.how-to-apply'
import { Route as LangListingsForSaleRouteImport } from './routes/$lang/listings.for-sale'
import { Route as LangListingsForRentRouteImport } from './routes/$lang/listings.for-rent'
import { Route as LangListingsIdRouteImport } from './routes/$lang/listings.$id'
import { Route as LangAccountSettingsRouteImport } from './routes/$lang/account.settings'
import { Route as LangAccountApplicationsRouteImport } from './routes/$lang/account.applications'
import { Route as ListingsIdNextStepsDocumentsRouteImport } from './routes/listings.$id.next-steps.documents'
import { Route as ListingsIdApplyIntroRouteImport } from './routes/listings.$id.apply.intro'
import { Route as LangListingsIdNextStepsRouteImport } from './routes/$lang/listings.$id.next-steps'
import { Route as LangListingsIdHowToApplyRouteImport } from './routes/$lang/listings.$id.how-to-apply'
import { Route as LangListingsIdNextStepsDocumentsRouteImport } from './routes/$lang/listings.$id.next-steps.documents'
import { Route as LangListingsIdApplyIntroRouteImport } from './routes/$lang/listings.$id.apply.intro'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyApplicationsRoute = MyApplicationsRouteImport.update({
  id: '/my-applications',
  path: '/my-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAccountRoute = MyAccountRouteImport.update({
  id: '/my-account',
  path: '/my-account',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingCounselorsRoute = HousingCounselorsRouteImport.update({
  id: '/housing-counselors',
  path: '/housing-counselors',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAssistanceRoute = GetAssistanceRouteImport.update({
  id: '/get-assistance',
  path: '/get-assistance',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentChecklistRoute = DocumentChecklistRouteImport.update({
  id: '/document-checklist',
  path: '/document-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdditionalResourcesRoute = AdditionalResourcesRouteImport.update({
  id: '/additional-resources',
  path: '/additional-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const ListingsForSaleRoute = ListingsForSaleRouteImport.update({
  id: '/listings/for-sale',
  path: '/listings/for-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsForRentRoute = ListingsForRentRouteImport.update({
  id: '/listings/for-rent',
  path: '/listings/for-rent',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountApplicationsRoute = AccountApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AccountRoute,
} as any)
const LangSignInRoute = LangSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => LangRoute,
} as any)
const LangResetPasswordRoute = LangResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LangRoute,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangRoute,
} as any)
const LangMyApplicationsRoute = LangMyApplicationsRouteImport.update({
  id: '/my-applications',
  path: '/my-applications',
  getParentRoute: () => LangRoute,
} as any)
const LangMyAccountRoute = LangMyAccountRouteImport.update({
  id: '/my-account',
  path: '/my-account',
  getParentRoute: () => LangRoute,
} as any)
const LangHousingCounselorsRoute = LangHousingCounselorsRouteImport.update({
  id: '/housing-counselors',
  path: '/housing-counselors',
  getParentRoute: () => LangRoute,
} as any)
const LangGetAssistanceRoute = LangGetAssistanceRouteImport.update({
  id: '/get-assistance',
  path: '/get-assistance',
  getParentRoute: () => LangRoute,
} as any)
const LangForgotPasswordRoute = LangForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => LangRoute,
} as any)
const LangDocumentChecklistRoute = LangDocumentChecklistRouteImport.update({
  id: '/document-checklist',
  path: '/document-checklist',
  getParentRoute: () => LangRoute,
} as any)
const LangDisclaimerRoute = LangDisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => LangRoute,
} as any)
const LangCreateAccountRoute = LangCreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => LangRoute,
} as any)
const LangAdditionalResourcesRoute = LangAdditionalResourcesRouteImport.update({
  id: '/additional-resources',
  path: '/additional-resources',
  getParentRoute: () => LangRoute,
} as any)
const LangAccountRoute = LangAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LangRoute,
} as any)
const ListingsIdNextStepsRoute = ListingsIdNextStepsRouteImport.update({
  id: '/next-steps',
  path: '/next-steps',
  getParentRoute: () => ListingsIdRoute,
} as any)
const ListingsIdHowToApplyRoute = ListingsIdHowToApplyRouteImport.update({
  id: '/how-to-apply',
  path: '/how-to-apply',
  getParentRoute: () => ListingsIdRoute,
} as any)
const LangListingsForSaleRoute = LangListingsForSaleRouteImport.update({
  id: '/listings/for-sale',
  path: '/listings/for-sale',
  getParentRoute: () => LangRoute,
} as any)
const LangListingsForRentRoute = LangListingsForRentRouteImport.update({
  id: '/listings/for-rent',
  path: '/listings/for-rent',
  getParentRoute: () => LangRoute,
} as any)
const LangListingsIdRoute = LangListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => LangRoute,
} as any)
const LangAccountSettingsRoute = LangAccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LangAccountRoute,
} as any)
const LangAccountApplicationsRoute = LangAccountApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => LangAccountRoute,
} as any)
const ListingsIdNextStepsDocumentsRoute =
  ListingsIdNextStepsDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ListingsIdNextStepsRoute,
  } as any)
const ListingsIdApplyIntroRoute = ListingsIdApplyIntroRouteImport.update({
  id: '/apply/intro',
  path: '/apply/intro',
  getParentRoute: () => ListingsIdRoute,
} as any)
const LangListingsIdNextStepsRoute = LangListingsIdNextStepsRouteImport.update({
  id: '/next-steps',
  path: '/next-steps',
  getParentRoute: () => LangListingsIdRoute,
} as any)
const LangListingsIdHowToApplyRoute =
  LangListingsIdHowToApplyRouteImport.update({
    id: '/how-to-apply',
    path: '/how-to-apply',
    getParentRoute: () => LangListingsIdRoute,
  } as any)
const LangListingsIdNextStepsDocumentsRoute =
  LangListingsIdNextStepsDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => LangListingsIdNextStepsRoute,
  } as any)
const LangListingsIdApplyIntroRoute =
  LangListingsIdApplyIntroRouteImport.update({
    id: '/apply/intro',
    path: '/apply/intro',
    getParentRoute: () => LangListingsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/additional-resources': typeof AdditionalResourcesRoute
  '/create-account': typeof CreateAccountRoute
  '/disclaimer': typeof DisclaimerRoute
  '/document-checklist': typeof DocumentChecklistRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-assistance': typeof GetAssistanceRoute
  '/housing-counselors': typeof HousingCounselorsRoute
  '/my-account': typeof MyAccountRoute
  '/my-applications': typeof MyApplicationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/$lang/account': typeof LangAccountRouteWithChildren
  '/$lang/additional-resources': typeof LangAdditionalResourcesRoute
  '/$lang/create-account': typeof LangCreateAccountRoute
  '/$lang/disclaimer': typeof LangDisclaimerRoute
  '/$lang/document-checklist': typeof LangDocumentChecklistRoute
  '/$lang/forgot-password': typeof LangForgotPasswordRoute
  '/$lang/get-assistance': typeof LangGetAssistanceRoute
  '/$lang/housing-counselors': typeof LangHousingCounselorsRoute
  '/$lang/my-account': typeof LangMyAccountRoute
  '/$lang/my-applications': typeof LangMyApplicationsRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/reset-password': typeof LangResetPasswordRoute
  '/$lang/sign-in': typeof LangSignInRoute
  '/account/applications': typeof AccountApplicationsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/listings/$id': typeof ListingsIdRouteWithChildren
  '/listings/for-rent': typeof ListingsForRentRoute
  '/listings/for-sale': typeof ListingsForSaleRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/account/applications': typeof LangAccountApplicationsRoute
  '/$lang/account/settings': typeof LangAccountSettingsRoute
  '/$lang/listings/$id': typeof LangListingsIdRouteWithChildren
  '/$lang/listings/for-rent': typeof LangListingsForRentRoute
  '/$lang/listings/for-sale': typeof LangListingsForSaleRoute
  '/listings/$id/how-to-apply': typeof ListingsIdHowToApplyRoute
  '/listings/$id/next-steps': typeof ListingsIdNextStepsRouteWithChildren
  '/$lang/listings/$id/how-to-apply': typeof LangListingsIdHowToApplyRoute
  '/$lang/listings/$id/next-steps': typeof LangListingsIdNextStepsRouteWithChildren
  '/listings/$id/apply/intro': typeof ListingsIdApplyIntroRoute
  '/listings/$id/next-steps/documents': typeof ListingsIdNextStepsDocumentsRoute
  '/$lang/listings/$id/apply/intro': typeof LangListingsIdApplyIntroRoute
  '/$lang/listings/$id/next-steps/documents': typeof LangListingsIdNextStepsDocumentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/additional-resources': typeof AdditionalResourcesRoute
  '/create-account': typeof CreateAccountRoute
  '/disclaimer': typeof DisclaimerRoute
  '/document-checklist': typeof DocumentChecklistRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-assistance': typeof GetAssistanceRoute
  '/housing-counselors': typeof HousingCounselorsRoute
  '/my-account': typeof MyAccountRoute
  '/my-applications': typeof MyApplicationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/$lang/account': typeof LangAccountRouteWithChildren
  '/$lang/additional-resources': typeof LangAdditionalResourcesRoute
  '/$lang/create-account': typeof LangCreateAccountRoute
  '/$lang/disclaimer': typeof LangDisclaimerRoute
  '/$lang/document-checklist': typeof LangDocumentChecklistRoute
  '/$lang/forgot-password': typeof LangForgotPasswordRoute
  '/$lang/get-assistance': typeof LangGetAssistanceRoute
  '/$lang/housing-counselors': typeof LangHousingCounselorsRoute
  '/$lang/my-account': typeof LangMyAccountRoute
  '/$lang/my-applications': typeof LangMyApplicationsRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/reset-password': typeof LangResetPasswordRoute
  '/$lang/sign-in': typeof LangSignInRoute
  '/account/applications': typeof AccountApplicationsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/listings/$id': typeof ListingsIdRouteWithChildren
  '/listings/for-rent': typeof ListingsForRentRoute
  '/listings/for-sale': typeof ListingsForSaleRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/account/applications': typeof LangAccountApplicationsRoute
  '/$lang/account/settings': typeof LangAccountSettingsRoute
  '/$lang/listings/$id': typeof LangListingsIdRouteWithChildren
  '/$lang/listings/for-rent': typeof LangListingsForRentRoute
  '/$lang/listings/for-sale': typeof LangListingsForSaleRoute
  '/listings/$id/how-to-apply': typeof ListingsIdHowToApplyRoute
  '/listings/$id/next-steps': typeof ListingsIdNextStepsRouteWithChildren
  '/$lang/listings/$id/how-to-apply': typeof LangListingsIdHowToApplyRoute
  '/$lang/listings/$id/next-steps': typeof LangListingsIdNextStepsRouteWithChildren
  '/listings/$id/apply/intro': typeof ListingsIdApplyIntroRoute
  '/listings/$id/next-steps/documents': typeof ListingsIdNextStepsDocumentsRoute
  '/$lang/listings/$id/apply/intro': typeof LangListingsIdApplyIntroRoute
  '/$lang/listings/$id/next-steps/documents': typeof LangListingsIdNextStepsDocumentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/additional-resources': typeof AdditionalResourcesRoute
  '/create-account': typeof CreateAccountRoute
  '/disclaimer': typeof DisclaimerRoute
  '/document-checklist': typeof DocumentChecklistRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-assistance': typeof GetAssistanceRoute
  '/housing-counselors': typeof HousingCounselorsRoute
  '/my-account': typeof MyAccountRoute
  '/my-applications': typeof MyApplicationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/$lang/account': typeof LangAccountRouteWithChildren
  '/$lang/additional-resources': typeof LangAdditionalResourcesRoute
  '/$lang/create-account': typeof LangCreateAccountRoute
  '/$lang/disclaimer': typeof LangDisclaimerRoute
  '/$lang/document-checklist': typeof LangDocumentChecklistRoute
  '/$lang/forgot-password': typeof LangForgotPasswordRoute
  '/$lang/get-assistance': typeof LangGetAssistanceRoute
  '/$lang/housing-counselors': typeof LangHousingCounselorsRoute
  '/$lang/my-account': typeof LangMyAccountRoute
  '/$lang/my-applications': typeof LangMyApplicationsRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/reset-password': typeof LangResetPasswordRoute
  '/$lang/sign-in': typeof LangSignInRoute
  '/account/applications': typeof AccountApplicationsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/listings/$id': typeof ListingsIdRouteWithChildren
  '/listings/for-rent': typeof ListingsForRentRoute
  '/listings/for-sale': typeof ListingsForSaleRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/account/applications': typeof LangAccountApplicationsRoute
  '/$lang/account/settings': typeof LangAccountSettingsRoute
  '/$lang/listings/$id': typeof LangListingsIdRouteWithChildren
  '/$lang/listings/for-rent': typeof LangListingsForRentRoute
  '/$lang/listings/for-sale': typeof LangListingsForSaleRoute
  '/listings/$id/how-to-apply': typeof ListingsIdHowToApplyRoute
  '/listings/$id/next-steps': typeof ListingsIdNextStepsRouteWithChildren
  '/$lang/listings/$id/how-to-apply': typeof LangListingsIdHowToApplyRoute
  '/$lang/listings/$id/next-steps': typeof LangListingsIdNextStepsRouteWithChildren
  '/listings/$id/apply/intro': typeof ListingsIdApplyIntroRoute
  '/listings/$id/next-steps/documents': typeof ListingsIdNextStepsDocumentsRoute
  '/$lang/listings/$id/apply/intro': typeof LangListingsIdApplyIntroRoute
  '/$lang/listings/$id/next-steps/documents': typeof LangListingsIdNextStepsDocumentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/account'
    | '/additional-resources'
    | '/create-account'
    | '/disclaimer'
    | '/document-checklist'
    | '/forgot-password'
    | '/get-assistance'
    | '/housing-counselors'
    | '/my-account'
    | '/my-applications'
    | '/privacy'
    | '/reset-password'
    | '/sign-in'
    | '/$lang/account'
    | '/$lang/additional-resources'
    | '/$lang/create-account'
    | '/$lang/disclaimer'
    | '/$lang/document-checklist'
    | '/$lang/forgot-password'
    | '/$lang/get-assistance'
    | '/$lang/housing-counselors'
    | '/$lang/my-account'
    | '/$lang/my-applications'
    | '/$lang/privacy'
    | '/$lang/reset-password'
    | '/$lang/sign-in'
    | '/account/applications'
    | '/account/settings'
    | '/listings/$id'
    | '/listings/for-rent'
    | '/listings/for-sale'
    | '/$lang/'
    | '/$lang/account/applications'
    | '/$lang/account/settings'
    | '/$lang/listings/$id'
    | '/$lang/listings/for-rent'
    | '/$lang/listings/for-sale'
    | '/listings/$id/how-to-apply'
    | '/listings/$id/next-steps'
    | '/$lang/listings/$id/how-to-apply'
    | '/$lang/listings/$id/next-steps'
    | '/listings/$id/apply/intro'
    | '/listings/$id/next-steps/documents'
    | '/$lang/listings/$id/apply/intro'
    | '/$lang/listings/$id/next-steps/documents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/additional-resources'
    | '/create-account'
    | '/disclaimer'
    | '/document-checklist'
    | '/forgot-password'
    | '/get-assistance'
    | '/housing-counselors'
    | '/my-account'
    | '/my-applications'
    | '/privacy'
    | '/reset-password'
    | '/sign-in'
    | '/$lang/account'
    | '/$lang/additional-resources'
    | '/$lang/create-account'
    | '/$lang/disclaimer'
    | '/$lang/document-checklist'
    | '/$lang/forgot-password'
    | '/$lang/get-assistance'
    | '/$lang/housing-counselors'
    | '/$lang/my-account'
    | '/$lang/my-applications'
    | '/$lang/privacy'
    | '/$lang/reset-password'
    | '/$lang/sign-in'
    | '/account/applications'
    | '/account/settings'
    | '/listings/$id'
    | '/listings/for-rent'
    | '/listings/for-sale'
    | '/$lang'
    | '/$lang/account/applications'
    | '/$lang/account/settings'
    | '/$lang/listings/$id'
    | '/$lang/listings/for-rent'
    | '/$lang/listings/for-sale'
    | '/listings/$id/how-to-apply'
    | '/listings/$id/next-steps'
    | '/$lang/listings/$id/how-to-apply'
    | '/$lang/listings/$id/next-steps'
    | '/listings/$id/apply/intro'
    | '/listings/$id/next-steps/documents'
    | '/$lang/listings/$id/apply/intro'
    | '/$lang/listings/$id/next-steps/documents'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/account'
    | '/additional-resources'
    | '/create-account'
    | '/disclaimer'
    | '/document-checklist'
    | '/forgot-password'
    | '/get-assistance'
    | '/housing-counselors'
    | '/my-account'
    | '/my-applications'
    | '/privacy'
    | '/reset-password'
    | '/sign-in'
    | '/$lang/account'
    | '/$lang/additional-resources'
    | '/$lang/create-account'
    | '/$lang/disclaimer'
    | '/$lang/document-checklist'
    | '/$lang/forgot-password'
    | '/$lang/get-assistance'
    | '/$lang/housing-counselors'
    | '/$lang/my-account'
    | '/$lang/my-applications'
    | '/$lang/privacy'
    | '/$lang/reset-password'
    | '/$lang/sign-in'
    | '/account/applications'
    | '/account/settings'
    | '/listings/$id'
    | '/listings/for-rent'
    | '/listings/for-sale'
    | '/$lang/'
    | '/$lang/account/applications'
    | '/$lang/account/settings'
    | '/$lang/listings/$id'
    | '/$lang/listings/for-rent'
    | '/$lang/listings/for-sale'
    | '/listings/$id/how-to-apply'
    | '/listings/$id/next-steps'
    | '/$lang/listings/$id/how-to-apply'
    | '/$lang/listings/$id/next-steps'
    | '/listings/$id/apply/intro'
    | '/listings/$id/next-steps/documents'
    | '/$lang/listings/$id/apply/intro'
    | '/$lang/listings/$id/next-steps/documents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  AdditionalResourcesRoute: typeof AdditionalResourcesRoute
  CreateAccountRoute: typeof CreateAccountRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DocumentChecklistRoute: typeof DocumentChecklistRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GetAssistanceRoute: typeof GetAssistanceRoute
  HousingCounselorsRoute: typeof HousingCounselorsRoute
  MyAccountRoute: typeof MyAccountRoute
  MyApplicationsRoute: typeof MyApplicationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  ListingsIdRoute: typeof ListingsIdRouteWithChildren
  ListingsForRentRoute: typeof ListingsForRentRoute
  ListingsForSaleRoute: typeof ListingsForSaleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-applications': {
      id: '/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof MyApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-account': {
      id: '/my-account'
      path: '/my-account'
      fullPath: '/my-account'
      preLoaderRoute: typeof MyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing-counselors': {
      id: '/housing-counselors'
      path: '/housing-counselors'
      fullPath: '/housing-counselors'
      preLoaderRoute: typeof HousingCounselorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-assistance': {
      id: '/get-assistance'
      path: '/get-assistance'
      fullPath: '/get-assistance'
      preLoaderRoute: typeof GetAssistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-checklist': {
      id: '/document-checklist'
      path: '/document-checklist'
      fullPath: '/document-checklist'
      preLoaderRoute: typeof DocumentChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/additional-resources': {
      id: '/additional-resources'
      path: '/additional-resources'
      fullPath: '/additional-resources'
      preLoaderRoute: typeof AdditionalResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/listings/for-sale': {
      id: '/listings/for-sale'
      path: '/listings/for-sale'
      fullPath: '/listings/for-sale'
      preLoaderRoute: typeof ListingsForSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/for-rent': {
      id: '/listings/for-rent'
      path: '/listings/for-rent'
      fullPath: '/listings/for-rent'
      preLoaderRoute: typeof ListingsForRentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/applications': {
      id: '/account/applications'
      path: '/applications'
      fullPath: '/account/applications'
      preLoaderRoute: typeof AccountApplicationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/$lang/sign-in': {
      id: '/$lang/sign-in'
      path: '/sign-in'
      fullPath: '/$lang/sign-in'
      preLoaderRoute: typeof LangSignInRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/reset-password': {
      id: '/$lang/reset-password'
      path: '/reset-password'
      fullPath: '/$lang/reset-password'
      preLoaderRoute: typeof LangResetPasswordRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/my-applications': {
      id: '/$lang/my-applications'
      path: '/my-applications'
      fullPath: '/$lang/my-applications'
      preLoaderRoute: typeof LangMyApplicationsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/my-account': {
      id: '/$lang/my-account'
      path: '/my-account'
      fullPath: '/$lang/my-account'
      preLoaderRoute: typeof LangMyAccountRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/housing-counselors': {
      id: '/$lang/housing-counselors'
      path: '/housing-counselors'
      fullPath: '/$lang/housing-counselors'
      preLoaderRoute: typeof LangHousingCounselorsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/get-assistance': {
      id: '/$lang/get-assistance'
      path: '/get-assistance'
      fullPath: '/$lang/get-assistance'
      preLoaderRoute: typeof LangGetAssistanceRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/forgot-password': {
      id: '/$lang/forgot-password'
      path: '/forgot-password'
      fullPath: '/$lang/forgot-password'
      preLoaderRoute: typeof LangForgotPasswordRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/document-checklist': {
      id: '/$lang/document-checklist'
      path: '/document-checklist'
      fullPath: '/$lang/document-checklist'
      preLoaderRoute: typeof LangDocumentChecklistRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/disclaimer': {
      id: '/$lang/disclaimer'
      path: '/disclaimer'
      fullPath: '/$lang/disclaimer'
      preLoaderRoute: typeof LangDisclaimerRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/create-account': {
      id: '/$lang/create-account'
      path: '/create-account'
      fullPath: '/$lang/create-account'
      preLoaderRoute: typeof LangCreateAccountRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/additional-resources': {
      id: '/$lang/additional-resources'
      path: '/additional-resources'
      fullPath: '/$lang/additional-resources'
      preLoaderRoute: typeof LangAdditionalResourcesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/account': {
      id: '/$lang/account'
      path: '/account'
      fullPath: '/$lang/account'
      preLoaderRoute: typeof LangAccountRouteImport
      parentRoute: typeof LangRoute
    }
    '/listings/$id/next-steps': {
      id: '/listings/$id/next-steps'
      path: '/next-steps'
      fullPath: '/listings/$id/next-steps'
      preLoaderRoute: typeof ListingsIdNextStepsRouteImport
      parentRoute: typeof ListingsIdRoute
    }
    '/listings/$id/how-to-apply': {
      id: '/listings/$id/how-to-apply'
      path: '/how-to-apply'
      fullPath: '/listings/$id/how-to-apply'
      preLoaderRoute: typeof ListingsIdHowToApplyRouteImport
      parentRoute: typeof ListingsIdRoute
    }
    '/$lang/listings/for-sale': {
      id: '/$lang/listings/for-sale'
      path: '/listings/for-sale'
      fullPath: '/$lang/listings/for-sale'
      preLoaderRoute: typeof LangListingsForSaleRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/listings/for-rent': {
      id: '/$lang/listings/for-rent'
      path: '/listings/for-rent'
      fullPath: '/$lang/listings/for-rent'
      preLoaderRoute: typeof LangListingsForRentRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/listings/$id': {
      id: '/$lang/listings/$id'
      path: '/listings/$id'
      fullPath: '/$lang/listings/$id'
      preLoaderRoute: typeof LangListingsIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/account/settings': {
      id: '/$lang/account/settings'
      path: '/settings'
      fullPath: '/$lang/account/settings'
      preLoaderRoute: typeof LangAccountSettingsRouteImport
      parentRoute: typeof LangAccountRoute
    }
    '/$lang/account/applications': {
      id: '/$lang/account/applications'
      path: '/applications'
      fullPath: '/$lang/account/applications'
      preLoaderRoute: typeof LangAccountApplicationsRouteImport
      parentRoute: typeof LangAccountRoute
    }
    '/listings/$id/next-steps/documents': {
      id: '/listings/$id/next-steps/documents'
      path: '/documents'
      fullPath: '/listings/$id/next-steps/documents'
      preLoaderRoute: typeof ListingsIdNextStepsDocumentsRouteImport
      parentRoute: typeof ListingsIdNextStepsRoute
    }
    '/listings/$id/apply/intro': {
      id: '/listings/$id/apply/intro'
      path: '/apply/intro'
      fullPath: '/listings/$id/apply/intro'
      preLoaderRoute: typeof ListingsIdApplyIntroRouteImport
      parentRoute: typeof ListingsIdRoute
    }
    '/$lang/listings/$id/next-steps': {
      id: '/$lang/listings/$id/next-steps'
      path: '/next-steps'
      fullPath: '/$lang/listings/$id/next-steps'
      preLoaderRoute: typeof LangListingsIdNextStepsRouteImport
      parentRoute: typeof LangListingsIdRoute
    }
    '/$lang/listings/$id/how-to-apply': {
      id: '/$lang/listings/$id/how-to-apply'
      path: '/how-to-apply'
      fullPath: '/$lang/listings/$id/how-to-apply'
      preLoaderRoute: typeof LangListingsIdHowToApplyRouteImport
      parentRoute: typeof LangListingsIdRoute
    }
    '/$lang/listings/$id/next-steps/documents': {
      id: '/$lang/listings/$id/next-steps/documents'
      path: '/documents'
      fullPath: '/$lang/listings/$id/next-steps/documents'
      preLoaderRoute: typeof LangListingsIdNextStepsDocumentsRouteImport
      parentRoute: typeof LangListingsIdNextStepsRoute
    }
    '/$lang/listings/$id/apply/intro': {
      id: '/$lang/listings/$id/apply/intro'
      path: '/apply/intro'
      fullPath: '/$lang/listings/$id/apply/intro'
      preLoaderRoute: typeof LangListingsIdApplyIntroRouteImport
      parentRoute: typeof LangListingsIdRoute
    }
  }
}

interface LangAccountRouteChildren {
  LangAccountApplicationsRoute: typeof LangAccountApplicationsRoute
  LangAccountSettingsRoute: typeof LangAccountSettingsRoute
}

const LangAccountRouteChildren: LangAccountRouteChildren = {
  LangAccountApplicationsRoute: LangAccountApplicationsRoute,
  LangAccountSettingsRoute: LangAccountSettingsRoute,
}

const LangAccountRouteWithChildren = LangAccountRoute._addFileChildren(
  LangAccountRouteChildren,
)

interface LangListingsIdNextStepsRouteChildren {
  LangListingsIdNextStepsDocumentsRoute: typeof LangListingsIdNextStepsDocumentsRoute
}

const LangListingsIdNextStepsRouteChildren: LangListingsIdNextStepsRouteChildren =
  {
    LangListingsIdNextStepsDocumentsRoute:
      LangListingsIdNextStepsDocumentsRoute,
  }

const LangListingsIdNextStepsRouteWithChildren =
  LangListingsIdNextStepsRoute._addFileChildren(
    LangListingsIdNextStepsRouteChildren,
  )

interface LangListingsIdRouteChildren {
  LangListingsIdHowToApplyRoute: typeof LangListingsIdHowToApplyRoute
  LangListingsIdNextStepsRoute: typeof LangListingsIdNextStepsRouteWithChildren
  LangListingsIdApplyIntroRoute: typeof LangListingsIdApplyIntroRoute
}

const LangListingsIdRouteChildren: LangListingsIdRouteChildren = {
  LangListingsIdHowToApplyRoute: LangListingsIdHowToApplyRoute,
  LangListingsIdNextStepsRoute: LangListingsIdNextStepsRouteWithChildren,
  LangListingsIdApplyIntroRoute: LangListingsIdApplyIntroRoute,
}

const LangListingsIdRouteWithChildren = LangListingsIdRoute._addFileChildren(
  LangListingsIdRouteChildren,
)

interface LangRouteChildren {
  LangAccountRoute: typeof LangAccountRouteWithChildren
  LangAdditionalResourcesRoute: typeof LangAdditionalResourcesRoute
  LangCreateAccountRoute: typeof LangCreateAccountRoute
  LangDisclaimerRoute: typeof LangDisclaimerRoute
  LangDocumentChecklistRoute: typeof LangDocumentChecklistRoute
  LangForgotPasswordRoute: typeof LangForgotPasswordRoute
  LangGetAssistanceRoute: typeof LangGetAssistanceRoute
  LangHousingCounselorsRoute: typeof LangHousingCounselorsRoute
  LangMyAccountRoute: typeof LangMyAccountRoute
  LangMyApplicationsRoute: typeof LangMyApplicationsRoute
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangResetPasswordRoute: typeof LangResetPasswordRoute
  LangSignInRoute: typeof LangSignInRoute
  LangIndexRoute: typeof LangIndexRoute
  LangListingsIdRoute: typeof LangListingsIdRouteWithChildren
  LangListingsForRentRoute: typeof LangListingsForRentRoute
  LangListingsForSaleRoute: typeof LangListingsForSaleRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAccountRoute: LangAccountRouteWithChildren,
  LangAdditionalResourcesRoute: LangAdditionalResourcesRoute,
  LangCreateAccountRoute: LangCreateAccountRoute,
  LangDisclaimerRoute: LangDisclaimerRoute,
  LangDocumentChecklistRoute: LangDocumentChecklistRoute,
  LangForgotPasswordRoute: LangForgotPasswordRoute,
  LangGetAssistanceRoute: LangGetAssistanceRoute,
  LangHousingCounselorsRoute: LangHousingCounselorsRoute,
  LangMyAccountRoute: LangMyAccountRoute,
  LangMyApplicationsRoute: LangMyApplicationsRoute,
  LangPrivacyRoute: LangPrivacyRoute,
  LangResetPasswordRoute: LangResetPasswordRoute,
  LangSignInRoute: LangSignInRoute,
  LangIndexRoute: LangIndexRoute,
  LangListingsIdRoute: LangListingsIdRouteWithChildren,
  LangListingsForRentRoute: LangListingsForRentRoute,
  LangListingsForSaleRoute: LangListingsForSaleRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface AccountRouteChildren {
  AccountApplicationsRoute: typeof AccountApplicationsRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountApplicationsRoute: AccountApplicationsRoute,
  AccountSettingsRoute: AccountSettingsRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface ListingsIdNextStepsRouteChildren {
  ListingsIdNextStepsDocumentsRoute: typeof ListingsIdNextStepsDocumentsRoute
}

const ListingsIdNextStepsRouteChildren: ListingsIdNextStepsRouteChildren = {
  ListingsIdNextStepsDocumentsRoute: ListingsIdNextStepsDocumentsRoute,
}

const ListingsIdNextStepsRouteWithChildren =
  ListingsIdNextStepsRoute._addFileChildren(ListingsIdNextStepsRouteChildren)

interface ListingsIdRouteChildren {
  ListingsIdHowToApplyRoute: typeof ListingsIdHowToApplyRoute
  ListingsIdNextStepsRoute: typeof ListingsIdNextStepsRouteWithChildren
  ListingsIdApplyIntroRoute: typeof ListingsIdApplyIntroRoute
}

const ListingsIdRouteChildren: ListingsIdRouteChildren = {
  ListingsIdHowToApplyRoute: ListingsIdHowToApplyRoute,
  ListingsIdNextStepsRoute: ListingsIdNextStepsRouteWithChildren,
  ListingsIdApplyIntroRoute: ListingsIdApplyIntroRoute,
}

const ListingsIdRouteWithChildren = ListingsIdRoute._addFileChildren(
  ListingsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  AdditionalResourcesRoute: AdditionalResourcesRoute,
  CreateAccountRoute: CreateAccountRoute,
  DisclaimerRoute: DisclaimerRoute,
  DocumentChecklistRoute: DocumentChecklistRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GetAssistanceRoute: GetAssistanceRoute,
  HousingCounselorsRoute: HousingCounselorsRoute,
  MyAccountRoute: MyAccountRoute,
  MyApplicationsRoute: MyApplicationsRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  ListingsIdRoute: ListingsIdRouteWithChildren,
  ListingsForRentRoute: ListingsForRentRoute,
  ListingsForSaleRoute: ListingsForSaleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
